name: docs

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 21 * * 0"
env:
  BOT_PASSWORD: ${{ secrets.BOT_PASSWORD }}
  BOT_USERNAME: ${{ secrets.BOT_USERNAME }}
  COOKIES: ${{ secrets.COOKIES }}
  WIKI_NAME: ${{ secrets.WIKI_NAME }}
  WIKI_SITE: ${{ secrets.WIKI_SITE }}

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          # “最近更新时间” 等 git 日志相关信息，需要拉取全部提交记录
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          # 选择要使用的 node 版本
          node-version: "18"
      # 如果缓存没有命中，安装依赖
      - name: Install dependencies
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm install

      # 运行构建脚本
      - name: Next Docs to MCS Wiki
        run: npm run start
        env:
          BOT_PASSWORD: ${{ env.BOT_PASSWORD }}
          BOT_USERNAME: ${{ env.BOT_USERNAME }}
          COOKIES: ${{ env.COOKIES }}
          WIKI_NAME: ${{ env.WIKI_NAME }}
          WIKI_SITE: ${{ env.WIKI_SITE }}

      # 查看 workflow 的文档来获取更多信息
      # @see https://github.com/crazy-max/ghaction-github-pages
