name: docs

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 21 * * 0"
env:
  # @see https://docs.github.com/cn/actions/reference/authentication-in-a-workflow#about-the-github_token-secret

  BOT_PASSWORD: ${{ secrets.BOT_PASSWORD }}
  BOT_USERNAME: ${{ secrets.BOT_USERNAME }}
  COOKIES: ${{ secrets.COOKIES }}
  WIKI_NAME: ${{ secrets.WIKI_NAME }}
  WIKI_SITE: ${{ secrets.WIKI_SITE }}
jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          # “最近更新时间” 等 git 日志相关信息，需要拉取全部提交记录
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          # 选择要使用的 node 版本
          node-version: "16"

      # 缓存 node_modules
      - name: Cache dependencies
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      # 如果缓存没有命中，安装依赖
      - name: Install dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn --frozen-lockfile

      # 运行构建脚本
      - name: Next Docs to MCS Wiki
        run: yarn start

      # 查看 workflow 的文档来获取更多信息
      # @see https://github.com/crazy-max/ghaction-github-pages
